const LOGIN = {
  START: "LOGIN_START",
  SUCCESS: "LOGIN_SUCCESS",
  FAIL: "LOGIN_FAIL",
};

const REGISTER = {
  START: "REGISTER_START",
  SUCCESS: "REGISTER_SUCCESS",
  FAIL: "REGISTER_FAIL",
};

const LOGOUT = "LOGOUT";

export { LOGOUT, LOGIN, REGISTER };
